
package com.systemsat.ws.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientesSoap", targetNamespace = "http://systemsat.gslog.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientesSoap {


    /**
     * 
     * @param senha
     * @param empCliente
     * @param login
     * @return
     *     returns com.systemsat.ws.cliente.ArrayOfCliente
     */
    @WebMethod(operationName = "Lista_Cliente", action = "http://systemsat.gslog.webservice/Lista_Cliente")
    @WebResult(name = "Lista_ClienteResult", targetNamespace = "http://systemsat.gslog.webservice/")
    @RequestWrapper(localName = "Lista_Cliente", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.cliente.ListaCliente")
    @ResponseWrapper(localName = "Lista_ClienteResponse", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.cliente.ListaClienteResponse")
    public ArrayOfCliente listaCliente(
        @WebParam(name = "EmpCliente", targetNamespace = "http://systemsat.gslog.webservice/")
        String empCliente,
        @WebParam(name = "Login", targetNamespace = "http://systemsat.gslog.webservice/")
        String login,
        @WebParam(name = "Senha", targetNamespace = "http://systemsat.gslog.webservice/")
        String senha);

}
