
package com.systemsat.ws.posicao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PosicoesSoap", targetNamespace = "http://systemsat.gslog.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PosicoesSoap {


    /**
     * 
     * @param senha
     * @param empCliente
     * @param login
     * @return
     *     returns com.systemsat.ws.posicao.ArrayOfPosicao
     */
    @WebMethod(operationName = "Lista_UltimasPosicoes", action = "http://systemsat.gslog.webservice/Lista_UltimasPosicoes")
    @WebResult(name = "Lista_UltimasPosicoesResult", targetNamespace = "http://systemsat.gslog.webservice/")
    @RequestWrapper(localName = "Lista_UltimasPosicoes", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaUltimasPosicoes")
    @ResponseWrapper(localName = "Lista_UltimasPosicoesResponse", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaUltimasPosicoesResponse")
    public ArrayOfPosicao listaUltimasPosicoes(
        @WebParam(name = "EmpCliente", targetNamespace = "http://systemsat.gslog.webservice/")
        String empCliente,
        @WebParam(name = "Login", targetNamespace = "http://systemsat.gslog.webservice/")
        String login,
        @WebParam(name = "Senha", targetNamespace = "http://systemsat.gslog.webservice/")
        String senha);

    /**
     * 
     * @param senha
     * @param empCliente
     * @param descricaoVeiculo
     * @param login
     * @return
     *     returns com.systemsat.ws.posicao.ArrayOfPosicao
     */
    @WebMethod(operationName = "Lista_UltimasPosicoesPorVeiculo", action = "http://systemsat.gslog.webservice/Lista_UltimasPosicoesPorVeiculo")
    @WebResult(name = "Lista_UltimasPosicoesPorVeiculoResult", targetNamespace = "http://systemsat.gslog.webservice/")
    @RequestWrapper(localName = "Lista_UltimasPosicoesPorVeiculo", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaUltimasPosicoesPorVeiculo")
    @ResponseWrapper(localName = "Lista_UltimasPosicoesPorVeiculoResponse", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaUltimasPosicoesPorVeiculoResponse")
    public ArrayOfPosicao listaUltimasPosicoesPorVeiculo(
        @WebParam(name = "EmpCliente", targetNamespace = "http://systemsat.gslog.webservice/")
        String empCliente,
        @WebParam(name = "Login", targetNamespace = "http://systemsat.gslog.webservice/")
        String login,
        @WebParam(name = "Senha", targetNamespace = "http://systemsat.gslog.webservice/")
        String senha,
        @WebParam(name = "DescricaoVeiculo", targetNamespace = "http://systemsat.gslog.webservice/")
        String descricaoVeiculo);

    /**
     * 
     * @param senha
     * @param empCliente
     * @param descricaoVeiculo
     * @param dataInicial
     * @param login
     * @param dataFinal
     * @return
     *     returns com.systemsat.ws.posicao.ArrayOfPosicao
     */
    @WebMethod(operationName = "Lista_HistoricoPosicoesPorVeiculo", action = "http://systemsat.gslog.webservice/Lista_HistoricoPosicoesPorVeiculo")
    @WebResult(name = "Lista_HistoricoPosicoesPorVeiculoResult", targetNamespace = "http://systemsat.gslog.webservice/")
    @RequestWrapper(localName = "Lista_HistoricoPosicoesPorVeiculo", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaHistoricoPosicoesPorVeiculo")
    @ResponseWrapper(localName = "Lista_HistoricoPosicoesPorVeiculoResponse", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaHistoricoPosicoesPorVeiculoResponse")
    public ArrayOfPosicao listaHistoricoPosicoesPorVeiculo(
        @WebParam(name = "EmpCliente", targetNamespace = "http://systemsat.gslog.webservice/")
        String empCliente,
        @WebParam(name = "Login", targetNamespace = "http://systemsat.gslog.webservice/")
        String login,
        @WebParam(name = "Senha", targetNamespace = "http://systemsat.gslog.webservice/")
        String senha,
        @WebParam(name = "DataInicial", targetNamespace = "http://systemsat.gslog.webservice/")
        String dataInicial,
        @WebParam(name = "DataFinal", targetNamespace = "http://systemsat.gslog.webservice/")
        String dataFinal,
        @WebParam(name = "DescricaoVeiculo", targetNamespace = "http://systemsat.gslog.webservice/")
        String descricaoVeiculo);

    /**
     * 
     * @param senha
     * @param empCliente
     * @param descricaoVeiculo
     * @param dataInicial
     * @param login
     * @param dataFinal
     * @return
     *     returns com.systemsat.ws.posicao.ArrayOfPosicao
     */
    @WebMethod(operationName = "Lista_AlertasPorVeiculo", action = "http://systemsat.gslog.webservice/Lista_AlertasPorVeiculo")
    @WebResult(name = "Lista_AlertasPorVeiculoResult", targetNamespace = "http://systemsat.gslog.webservice/")
    @RequestWrapper(localName = "Lista_AlertasPorVeiculo", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaAlertasPorVeiculo")
    @ResponseWrapper(localName = "Lista_AlertasPorVeiculoResponse", targetNamespace = "http://systemsat.gslog.webservice/", className = "com.systemsat.ws.posicao.ListaAlertasPorVeiculoResponse")
    public ArrayOfPosicao listaAlertasPorVeiculo(
        @WebParam(name = "EmpCliente", targetNamespace = "http://systemsat.gslog.webservice/")
        String empCliente,
        @WebParam(name = "Login", targetNamespace = "http://systemsat.gslog.webservice/")
        String login,
        @WebParam(name = "Senha", targetNamespace = "http://systemsat.gslog.webservice/")
        String senha,
        @WebParam(name = "DataInicial", targetNamespace = "http://systemsat.gslog.webservice/")
        String dataInicial,
        @WebParam(name = "DataFinal", targetNamespace = "http://systemsat.gslog.webservice/")
        String dataFinal,
        @WebParam(name = "DescricaoVeiculo", targetNamespace = "http://systemsat.gslog.webservice/")
        String descricaoVeiculo);

}
