
package com.systemsat.ws.posicao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Posicoes", targetNamespace = "http://systemsat.gslog.webservice/", wsdlLocation = "http://www.globalsearch.com.br/webservice/posicoes.asmx?wsdl")
public class Posicoes
    extends Service
{

    private final static URL POSICOES_WSDL_LOCATION;
    private final static WebServiceException POSICOES_EXCEPTION;
    private final static QName POSICOES_QNAME = new QName("http://systemsat.gslog.webservice/", "Posicoes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.globalsearch.com.br/webservice/posicoes.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSICOES_WSDL_LOCATION = url;
        POSICOES_EXCEPTION = e;
    }

    public Posicoes() {
        super(__getWsdlLocation(), POSICOES_QNAME);
    }

    public Posicoes(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSICOES_QNAME, features);
    }

    public Posicoes(URL wsdlLocation) {
        super(wsdlLocation, POSICOES_QNAME);
    }

    public Posicoes(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSICOES_QNAME, features);
    }

    public Posicoes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Posicoes(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PosicoesSoap
     */
    @WebEndpoint(name = "PosicoesSoap")
    public PosicoesSoap getPosicoesSoap() {
        return super.getPort(new QName("http://systemsat.gslog.webservice/", "PosicoesSoap"), PosicoesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PosicoesSoap
     */
    @WebEndpoint(name = "PosicoesSoap")
    public PosicoesSoap getPosicoesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://systemsat.gslog.webservice/", "PosicoesSoap"), PosicoesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PosicoesSoap
     */
    @WebEndpoint(name = "PosicoesSoap12")
    public PosicoesSoap getPosicoesSoap12() {
        return super.getPort(new QName("http://systemsat.gslog.webservice/", "PosicoesSoap12"), PosicoesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PosicoesSoap
     */
    @WebEndpoint(name = "PosicoesSoap12")
    public PosicoesSoap getPosicoesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://systemsat.gslog.webservice/", "PosicoesSoap12"), PosicoesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSICOES_EXCEPTION!= null) {
            throw POSICOES_EXCEPTION;
        }
        return POSICOES_WSDL_LOCATION;
    }

}
